"""empty message

Revision ID: 02f82c1fb311
Revises: a1e953c610cb
Create Date: 2018-06-06 09:14:10.568271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f82c1fb311'
down_revision = 'a1e953c610cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('cache_valid', sa.Boolean(), server_default='f', nullable=False))
    op.drop_column('nodes', 'cache_depth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('cache_depth', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('nodes', 'cache_valid')
    # ### end Alembic commands ###
