"""Add nodes.preferred

Revision ID: 4678451894c9
Revises: 51bb55927612
Create Date: 2018-11-23 11:46:57.322142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4678451894c9'
down_revision = '51bb55927612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('preferred', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'preferred')
    # ### end Alembic commands ###
