"""empty message

Revision ID: 51bb55927612
Revises: aacb0ce28ba6
Create Date: 2018-11-09 11:57:51.683806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bb55927612'
down_revision = 'aacb0ce28ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes_rejected_objects',
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.object_id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_nodes_rejected_objects_node_id'), 'nodes_rejected_objects', ['node_id'], unique=False)
    op.create_index(op.f('ix_nodes_rejected_objects_object_id'), 'nodes_rejected_objects', ['object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_rejected_objects_object_id'), table_name='nodes_rejected_objects')
    op.drop_index(op.f('ix_nodes_rejected_objects_node_id'), table_name='nodes_rejected_objects')
    op.drop_table('nodes_rejected_objects')
    # ### end Alembic commands ###
