"""Drop nodes._covariance, add log.data.

Revision ID: 77b9c8eb1df8
Revises: ac57b043449c
Create Date: 2018-09-03 12:04:53.853016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77b9c8eb1df8'
down_revision = 'ac57b043449c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('data', sa.Text(), nullable=True))
    op.drop_column('nodes', '_covariance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('_covariance', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('log', 'data')
    # ### end Alembic commands ###
