"""empty message

Revision ID: a1e953c610cb
Revises: 468d0564d1da
Create Date: 2018-05-29 11:50:31.493886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e953c610cb'
down_revision = '468d0564d1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('approved', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'approved')
    # ### end Alembic commands ###
