"""empty message

Revision ID: cb0b9c38b9fe
Revises: 20b499a891eb
Create Date: 2018-07-27 10:37:01.905630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0b9c38b9fe'
down_revision = '20b499a891eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_nodes_superparent_id'), 'nodes', ['superparent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_superparent_id'), table_name='nodes')
    # ### end Alembic commands ###
