"""Add projects.visible

Revision ID: db2a7b29511b
Revises: f414d71c50c3
Create Date: 2018-07-24 11:10:24.594564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2a7b29511b'
down_revision = 'f414d71c50c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('visible', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'visible')
    # ### end Alembic commands ###
