"""Create job. Add index nodes_objects.object_id.

Revision ID: fe6fec6b70a6
Revises: 8de87a72da91
Create Date: 2019-04-03 10:53:06.676924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6fec6b70a6'
down_revision = '8de87a72da91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['username'], ['users.username'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_nodes_objects_object_id'),
                    'nodes_objects', ['object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_objects_object_id'),
                  table_name='nodes_objects')
    op.drop_table('job')
    # ### end Alembic commands ###
