"""empty message

Revision ID: 03df35632254
Revises: 02f82c1fb311
Create Date: 2018-06-06 10:21:59.234527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03df35632254'
down_revision = '02f82c1fb311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('_n_objects', sa.BigInteger(), nullable=True))
    op.alter_column('nodes', '_recursive_n_objects', new_column_name = '_n_objects_deep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', '_n_objects_deep', new_column_name = '_recursive_n_objects')
    op.drop_column('nodes', '_n_objects')
    # ### end Alembic commands ###
