"""empty message

Revision ID: 20b499a891eb
Revises: 4790ac7b1bf8
Create Date: 2018-07-27 08:51:21.745073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b499a891eb'
down_revision = '4790ac7b1bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_nodes_parent_id'), 'nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_nodes_project_id'), 'nodes', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_project_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_parent_id'), table_name='nodes')
    # ### end Alembic commands ###
