"""Add nodes._covariance column

Revision ID: 309729a37f88
Revises: 52928669f064
Create Date: 2018-08-10 10:28:48.246317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309729a37f88'
down_revision = '52928669f064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('_covariance', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', '_covariance')
    # ### end Alembic commands ###
