"""empty message

Revision ID: 52928669f064
Revises: cb0b9c38b9fe
Create Date: 2018-08-03 08:16:19.610323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52928669f064'
down_revision = 'cb0b9c38b9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('_n_children', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', '_n_children')
    # ### end Alembic commands ###
