"""empty message

Revision ID: 8a467c1ab9b5
Revises: 6c1aaca139b1
Create Date: 2018-05-23 13:00:49.096446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a467c1ab9b5'
down_revision = '6c1aaca139b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('valid', sa.Boolean(), nullable=False, server_default = "FALSE"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'valid')
    # ### end Alembic commands ###
