"""Add nodes.filled

Revision ID: aacb0ce28ba6
Revises: 77b9c8eb1df8
Create Date: 2018-09-05 13:21:07.200665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacb0ce28ba6'
down_revision = '77b9c8eb1df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('filled', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'filled')
    # ### end Alembic commands ###
