"""Add objects.rand, drop nodes_objects.by_user.

Revision ID: ac57b043449c
Revises: 309729a37f88
Create Date: 2018-08-10 11:19:58.377749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac57b043449c'
down_revision = '309729a37f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes_objects', 'by_user')
    op.add_column('objects', sa.Column('rand', sa.Float(), server_default=sa.text('random()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'rand')
    op.add_column('nodes_objects', sa.Column('by_user', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
