"""empty message

Revision ID: f414d71c50c3
Revises: 03df35632254
Create Date: 2018-07-13 10:36:41.333877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f414d71c50c3'
down_revision = '03df35632254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('superparent_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('nodes_superparent_id_fkey', 'nodes', 'nodes', ['superparent_id'], ['node_id'], ondelete='SET NULL')
    op.add_column('nodes_objects', sa.Column('by_user', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes_objects', 'by_user')
    op.drop_constraint('nodes_superparent_id_fkey', 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'superparent_id')
    # ### end Alembic commands ###
