name: Build Docker Image

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: morphocluster/morphocluster:test
  LATEST_TAG: morphocluster/morphocluster:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          # Automatically load the single-platform build result to `docker images`:
          load: true
          tags: ${{ env.TEST_TAG }}
          file: docker/morphocluster/Dockerfile
      
      # -
      #   name: Test
      #   # TODO: Spin up docker compose with the image just built and execute tests
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}
      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          tags: ${{ env.LATEST_TAG }}
          push: false # Do not push right now (until stable)
          file: docker/morphocluster/Dockerfile
